"""empty message

Revision ID: b7091dd96686
Revises: 
Create Date: 2022-06-18 23:58:58.615547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7091dd96686'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_accounts',
    sa.Column('account_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_name', sa.String(length=128), nullable=False),
    sa.Column('account_email', sa.String(length=64), nullable=False),
    sa.Column('account_phone', sa.BigInteger(), nullable=False),
    sa.Column('account_country', sa.String(length=32), nullable=False),
    sa.Column('account_sex', sa.String(length=1), nullable=False),
    sa.Column('account_language', sa.String(length=16), nullable=False),
    sa.Column('account_verified', sa.Boolean(), nullable=False),
    sa.Column('user_birthdate', sa.Date(), nullable=False),
    sa.Column('user_age', sa.SmallInteger(), nullable=False),
    sa.Column('account_creation', sa.DateTime(), nullable=False),
    sa.Column('account_login', sa.String(length=128), nullable=False),
    sa.Column('account_password', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('account_id'),
    sa.UniqueConstraint('account_email'),
    sa.UniqueConstraint('account_login'),
    sa.UniqueConstraint('account_phone')
    )
    op.create_index('account_verified_index', 'user_accounts', ['account_verified'], unique=False, postgresql_using='hash')
    op.create_index(op.f('ix_user_accounts_user_age'), 'user_accounts', ['user_age'], unique=False)
    op.create_table('user_friends',
    sa.Column('user_account_id', sa.Integer(), nullable=False),
    sa.Column('friend_account_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['friend_account_id'], ['user_accounts.account_id'], ),
    sa.ForeignKeyConstraint(['user_account_id'], ['user_accounts.account_id'], ),
    sa.PrimaryKeyConstraint('user_account_id')
    )
    op.create_table('user_photos',
    sa.Column('photo_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('photo_name', sa.Text(), nullable=True),
    sa.Column('photo_size', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['user_accounts.account_id'], ),
    sa.PrimaryKeyConstraint('photo_id')
    )
    op.create_table('user_posts',
    sa.Column('post_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_text', sa.Text(), nullable=False),
    sa.Column('post_time', sa.DateTime(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['user_accounts.account_id'], ),
    sa.PrimaryKeyConstraint('post_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_posts')
    op.drop_table('user_photos')
    op.drop_table('user_friends')
    op.drop_index(op.f('ix_user_accounts_user_age'), table_name='user_accounts')
    op.drop_index('account_verified_index', table_name='user_accounts', postgresql_using='hash')
    op.drop_table('user_accounts')
    # ### end Alembic commands ###
